### ISSUE TITLE
Add bootloader info

### ISSUE THREAD

**Issue by Papiertig0r** [Protonerd/DIYino#1]
In the "DIYino_v1_User_Manual_draft_v03.pdf" is no information which setting you have to use in the Arduino IDE to succesfully upload sketches.

**Comment by Papiertig0r** [comment]
Please don't mind, I just realized it's a draft, sorry!

**Comment by Protonerd** [comment]
Hi Papiertig0r, I will certainly work also on that Chapter but due to the superb documentation on the Arduino site I will only add links and not describe it in detail. Arduino is part of what DIYino is, but it's a hardware and I can only give some general guidelines/quick start help for software development.

**Comment by Protonerd** [comment]
Oh, I realized I might have misunderstood your intent. Probably you referred to the setting which type of circuit to use.. it is the Nano.
